# Generated by Django 4.0.4 on 2022-06-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('solo_ida', models.BooleanField()),
                ('fecha_reserva', models.DateField()),
                ('valor_reserva', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.IntegerField()),
                ('sexo', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('id_avion_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.avion')),
                ('id_ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_destino', to='icarusProjectApp.ciudad')),
                ('id_ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_origen', to='icarusProjectApp.ciudad')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva_Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.reserva')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.vuelo')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.usuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tarjeta_credito', models.CharField(max_length=255)),
                ('numero_tarjeta', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('cvc', models.IntegerField()),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.reserva')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.usuario')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
