# Generated by Django 4.0.5 on 2022-06-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255, null=True, unique=True)),
                ('apellido', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('rut', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rol', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=255, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('solo_ida', models.BooleanField()),
                ('fecha_reserva', models.DateTimeField()),
                ('valor_reserva', models.IntegerField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('id_avion_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.avion')),
                ('id_ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_destino', to='icarusProjectApp.ciudad')),
                ('id_ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_origen', to='icarusProjectApp.ciudad')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva_Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.reserva')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.vuelo')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tarjeta_credito', models.CharField(max_length=255)),
                ('numero_tarjeta', models.BigIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('cvc', models.IntegerField()),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.reserva')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
