# Generated by Django 4.0.4 on 2022-06-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0003_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha_salida',
            field=models.DateField(),
        ),
    ]
