# Generated by Django 4.0.4 on 2022-07-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0007_vuelo_reservas_delete_reserva_vuelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='solo_ida',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='reservas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_vuelo',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='icarusProjectApp.vuelo'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='valor_vuelo',
            field=models.BigIntegerField(default=0),
        ),
    ]
