# Generated by Django 4.0.4 on 2022-06-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
