# Generated by Django 4.0.4 on 2022-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0008_alter_pago_options_remove_reserva_solo_ida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='rut_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_vuelo',
            new_name='vuelo',
        ),
    ]
