# Generated by Django 4.0.4 on 2022-07-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0012_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
