# Generated by Django 4.0.4 on 2022-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0015_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_reserva',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.CharField(max_length=255),
        ),
    ]
