# Generated by Django 4.0.4 on 2022-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarusProjectApp', '0016_remove_pago_id_reserva_alter_pago_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.CharField(max_length=255),
        ),
    ]
